### ISSUE TITLE
Complex-valued resampling

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/resampy#14]
Cython's fused types should make this trivial, but for whatever reason, it didn't work out of the box.

We may have to handle complex-valued data explicitly.

**Comment by Eric89GXL** [comment]
FYI the fused types with complex values gets a bit wonky. You can read a long discussion (struggle) I recently had with it [here] (https://github.com/scipy/scipy/pull/5186#issuecomment-151134013) or better, just look at [what the solution ended up being] (https://github.com/scipy/scipy/pull/5186/files#diff-7ba66555c716f6c3378715b191a095f8R44). Maybe there is something helpful in there for you.

**Comment by Eric89GXL** [comment]
...now it's coming back to me a bit -- the workaround was to make it so that whatever fused type `DTYPE_t` I used as an argument *was the only fused type in the signature*, but it was fine to use it for multiple arguments. When I used more than one fused type in the signature (so that e.g. the kernel argument and the data argument could be different types), it tried to make all versions of the function, some of which had incompatible types when used within the function. Cython provides no way to limit the set of argument combinations to generate functions for, so it seemed to be the only way out.

**Comment by bmcfee** [comment]
Aha, I kinda suspected it night be something like that. Thanks for confirming!

It does seem like the kind of thing that ought to be fixed in a future cython release though, so maybe we can just wait it out?

**Comment by Eric89GXL** [comment]
> It does seem like the kind of thing that ought to be fixed in a future cython release though, so maybe we can just wait it out?

I thought I opened an issue for it somewhere, but looking back I don't have any record of it. I should probably do that...

In any case, even once the request is opened, there's no telling how long it would take them to implement it. Maybe it's something that wouldn't be so hard to contribute ourselves. I'll try to find time to look into it.

In the case of my code, the extra overhead of casting both to the biggest type was assumed to be small, so it didn't seem like too bad a compromise (a bit of extra casting and mem use) to gain proper support for complex types. So my feeling is that it would depends on how much you'd have to compromise your code to implement the workaround.

**Comment by bmcfee** [comment]
Sure.. alternately, it wouldn't be terrible to just resample the imaginary and real components independently and then recombine them.



> So my feeling is that it would depends on how much you'd have to compromise your code to implement the workaround.

That would be easy, but I think it would invoke another data copy, so i'd like to avoid it if possible.

**Comment by bmcfee** [comment]
FWIW: #57 gives us complex-valued resampling for free, so we can close this out after merging.
