### ISSUE TITLE
Q: Comparison to / inclusion in SciPy?

### ISSUE THREAD

**Issue by larsoner** [bmcfee/resampy#31]
@choldgraf just pointed me to this repo. I haven't had much time to dig into it, but it looks like a promising method for resampling. Have you by chance looked at how it compares to the polyphase resampling recently added to SciPy [scipy.signal.resample_poly](http://scipy.github.io/devdocs/generated/scipy.signal.resample_poly.html#scipy.signal.resample_poly)? I imagine this might be faster (argument from authority since it's based on one of Julius O Smith's documents), but from the little bit I read they seem to share some ideas so I'm curious to what extent it is faster.

Any interest in eventually moving the functionality to `scipy.signal` at some point?

**Comment by bmcfee** [comment]
Cool! I didn't know there was a polyphase resampler in scipy, but I can try to crank out some comparisons tomorrow or Saturday during the sprints.

Re: integration with scipy, yes! I didn't go that route initially because I had a hard deadline for shipping this, but it would be great to merge. I'm a little wary about how the interface should look, since the precomputed filters are pretty useful but outside of the usual scipy style.

**Comment by Eric89GXL** [comment]
> I'm a little wary about how the interface should look, since the precomputed filters are pretty useful but outside of the usual scipy style.

I'm not sure of existing examples of this sort of thing inside SciPy, but if they bring substantial performance improvements it seems like a reasonable thing to me. We can discuss this over on SciPy eventually, but I assume the way it works now is that the filters get stored somewhere for fast access like a LUT? If so, is there some way a user could precompute them themselves, and (optionally) pass them into the function? That seems very likely to work for SciPy. If it is strongly preferred to save them to disk, then we could try to find a way to do that, but agree it would be harder.

**Comment by bmcfee** [comment]
> We can discuss this over on SciPy eventually, but I assume the way it works now is that the filters get stored somewhere for fast access like a LUT? If so, is there some way a user could precompute them themselves, and (optionally) pass them into the function?

Exactly: the coefficients are pre-computed and stored in a buffer which gets passed into the interpolator.  Because the same sets of coefficients are used so frequently (heh), we include pre-computed LUTs in npz files which can be referred to by name (eg, `kaiser_fast`, `kaiser_best`, etc).  This step isn't strictly necessary, but every little bit helps; it's pretty easy to do via pkg_resources, but I don't think there's precedent for this in scipy.  Moreover, if we in the future decide to include filters derived by numerical optimization (instead of sinc+kaiser), this would be the only way to go.

You can also provide parameters for the `filters.sinc_window` function to construct the filter coefficients on the fly, which is more in keeping with existing idioms in scipy (eg, fft window functions).

We don't provide a way for users to directly provide the LUT, since there are a couple of other parameters that need to be tracked (ie, the full output tuple from `sinc_window`).  It wouldn't be hard to expand the filter loader to allow user-supplied filters, but I'm not sure how often such a thing would get used.
