### ISSUE TITLE
API documentation broken

### ISSUE THREAD

**Issue by hagenw** [bmcfee/resampy#65]
If you have a look at https://resampy.readthedocs.io/en/stable/api.html, there is nothing documented at the moment. This is due to an error while running sphinx, which can be found on this page: https://readthedocs.org/projects/resampy/builds/7292423/. You have to click on the "python /home/docs/checkouts/readthedocs.org/user_builds/resampy/envs/0.2.1/bin/sphinx-build -T -b readthedocs -d _b" and you can see it. the important part is:
```
WARNING: autodoc: failed to import module 'resampy.core'; the following exception was raised:
No module named 'numba'
WARNING: autodoc: failed to import module 'resampy.filters'; the following exception was raised:
No module named 'numba'
```

It is not so easy to debug without having access to your readthedocs settings, but I guess you haven't ticked the following boxes under advanced settings?
![rtfd-advanced](https://user-images.githubusercontent.com/173624/55079025-ac288380-509b-11e9-98ba-2b0371be184d.png)

**Comment by bmcfee** [comment]
Thanks for noting this -- it was working at one point, so I'm not sure what happened.

Your suggestion to install the package in the rtd build environment is noted, but since that would trigger an entire scipy stack installation, I tend to avoid that.  Instead, the usual fix is to mock install the dependencies so that the documentation builds cleanly.  I'm not sure why that stopped working, but I'll try to get it fixed some time in the next few days.

**Comment by bmcfee** [comment]
Documentation build is fixed now.  Thanks for catching it!
